"""
timer.py
Sends two prompts to VSCode Claude at scheduled times using clipboard paste.
CLIPBOARD METHOD — the entire prompt is pasted atomically with Ctrl+V.
Never uses typewrite(), which breaks on newlines, special chars, and long strings.

Schedule:
  Prompt 1 → 04:30
  Prompt 2 → 05:20  (50 min later)

Usage:
  1. pip install pyautogui pyperclip
  2. Have the image for Prompt 1 already pasted/attached in the VSCode chat.
  3. Click inside the VSCode chat input so the cursor is blinking there.
  4. python timer.py
"""

import time
import datetime
import pyautogui
import pyperclip

TARGET_TIME_P1 = "04:30"
TARGET_TIME_P2 = "05:20"

# ─────────────────────────────────────────────────────────────────────────────
# PROMPT 1 — 04:30: HTML/Excel Label Sync, Counter Fix, and Save Status
# ─────────────────────────────────────────────────────────────────────────────

PROMPT_1 = """[Please refer to the image I have already provided in the chat context for my setup]. 

I am having issues with how my HTML UI handles an uploaded Excel file (generated by our AI labeler). I suspect the current JavaScript code in the HTML that parses and feeds the `.xlsx` data is flawed. I need you to fix the Excel loading and saving logic in the HTML file. 

Here are the specific requirements to fix:
1. **Label Synchronization:** When I upload the `.xlsx` file, the HTML UI must automatically update its chosen labels to match the ones already present in the uploaded Excel file. Currently, this automatic mapping is failing.
2. **Patent Counters:** There is a discrepancy in the patent pagination/counters. The counter from the Excel data and the counter originally on the HTML page are out of sync. They must be perfectly aligned, and the total number of patents shown in the UI must strictly match the actual row count/number of patents in the uploaded `.xlsx` file.
3. **Save Status Indicator:** I need a clear visual indicator added to the UI so I know exactly when a patent's data has been successfully saved back to the new `.xlsx` file and when it hasn't.

Please review the HTML's parsing logic and provide the corrected code to resolve these three issues."""

# ─────────────────────────────────────────────────────────────────────────────
# PROMPT 2 — 05:20: Taxonomy Cross-Reference (Excel vs. HTML)
# ─────────────────────────────────────────────────────────────────────────────

PROMPT_2 = """Please analyze the provided Excel file "ml_predict_labels_Batch_02.xlsx" and the HTML file "UI_for_taxonomy_caracterization_10.0.html". 

Your task is to prospect and cross-reference the labels between these two files:
1. Check if all the labels currently used in the `.xlsx` file perfectly match the possible label options defined in the HTML file's taxonomy.
2. Provide a detailed report of any discrepancies. Specifically, list any labels present in the Excel file that are missing from the HTML taxonomy, or vice versa.
3. Suggest the necessary code or data adjustments to ensure they are 100% aligned."""


# ─────────────────────────────────────────────────────────────────────────────
# Timer logic — clipboard paste, all at once
# ─────────────────────────────────────────────────────────────────────────────

def send_prompt(label: str, text: str):
    """Copy text to clipboard and paste into the focused window atomically."""
    print(f"\n🚀 Sending {label}...")
    pyperclip.copy(text)
    time.sleep(0.4)                   # let clipboard settle
    pyautogui.hotkey("ctrl", "v")     # paste entire prompt at once
    time.sleep(0.6)                   # let the UI receive the paste
    pyautogui.press("enter")          # submit
    print(f"📨 {label} sent! ({len(text)} chars)")


def wait_until(target_hhmm: str, label: str):
    print(f"⏳ Waiting for {target_hhmm} to send {label}...")
    while True:
        now = datetime.datetime.now().strftime("%H:%M")
        if now == target_hhmm:
            return
        time.sleep(10)   # check every 10 seconds


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 60)
    print("  eVTOL Patent Pipeline — Overnight Prompt Timer")
    print("=" * 60)
    print(f"  Prompt 1 → {TARGET_TIME_P1}  (HTML/Excel Sync & UI Fixes)")
    print(f"  Prompt 2 → {TARGET_TIME_P2}  (Taxonomy Cross-Reference)")
    print()
    print("⚠️  BEFORE LEAVING:")
    print("    1. Ensure the image for Prompt 1 is attached in the chat.")
    print("    2. Click inside the VSCode chat input box.")
    print("    3. Make sure the cursor is blinking there.")
    print("    4. Do NOT touch the keyboard or mouse after that.")
    print("=" * 60)

    # ── Prompt 1 ──────────────────────────────────────────────────────────────
    wait_until(TARGET_TIME_P1, "Prompt 1")
    send_prompt("Prompt 1", PROMPT_1)

    # ── Wait until Prompt 2 ───────────────────────────────────────────────────
    print(f"\n⏳ Waiting for Prompt 2 at {TARGET_TIME_P2}...")
    wait_until(TARGET_TIME_P2, "Prompt 2")
    send_prompt("Prompt 2", PROMPT_2)

    print("\n🎉 Both prompts sent. Pipeline will run overnight.")