"""hybrid_powertrain_citations.py — the sentence(s) each powertrain proposal rests on (read 2026-09-27/30).
Each entry is a verbatim phrase from the PatSeer text; build_hybrid_powertrain_review_page.py finds the full
sentence, its section and paragraph number, and fails if a phrase is not found. An empty list = the patent never names
an energy source (the page then says so and shows the word counts).
"""
CITES = {
    # ---- A: battery-electric stated (alone / as an option / electric mode)
    "CN120024492A": ["power supply system is a fuel generator and/or a storage battery", "the power supply system 5 is a storage battery 52"],
    "CN120863869A": ["a high-energy-density battery is used as an energy source in the electric mode"],
    "CN120397241A": ["can work independently or cooperatively", "oil-driven engine (optional) provides long-range capability"],
    "DE102019001834A1": ["can come from an energy generation module (combustion engine + generator) or from an electrical storage unit (battery)"],
    "DE102019102189A1": ["If the aircraft is driven by one or more electric motors, it is preferred to use accumulators", "The rotors may also be driven by internal combustion engines"],
    "DE102019001240A1": ["relates to a purely electrically powered aircraft", "each of which has its own energy storage device", "internal combustion engine range extender"],
    "RU2757693C1": ["provided by storage batteries, hybrid electric generators with internal combustion engines"],
    "US2013264429A1": ["power supply of these electric motors is provided, preferably, by the electric batteries", "combustion engine 18 with electric generator 19"],
    "US2016200436A1": ["may be provided from one or both of two sources", "A second electrical source may be battery packs"],
    "US2016236774A1": ["provided by one of a battery or a generator"],
    "US2016347447A1": ["can be provided by a central generator, with for example a combustion engine, or by a battery"],
    "US2018044012A1": ["having a battery as the power source 114 connected to electric motors"],
    "US2018208305A1": ["comprise the primary power source providing high voltage direct current", "and/or the battery bank 156 may be delivered to the motors 164", "comprises an internal combustion engine and/or auxiliary power unit"],
    "US2020391879A1": ["make up the primary power source", "and/or the battery bank 156 may be delivered to motors 160", "comprises an internal combustion engine and/or auxiliary power unit"],
    "US2018354613A1": ["the propulsion devices are operable by electric energy which is stored in the electrical energy storage device", "optionally further comprises a charging system"],
    "US2019031333A1": ["wherein the electrical energy source is battery based", "may serve as the electrical energy source for propulsion assemblies 24"],
    "US2019100313A1": ["wherein the sole electrical energy source are batteries 58"],
    "US2020140079A1": ["wherein the sole electrical energy source are batteries 228"],
    "US2019135424A1": ["all-electric VTOL capable UAS", "batteries and/or conversion technologies such as generators"],
    "US2020023963A1": ["may comprise an electric power storage device such as a chemical battery", "Alternatively or in addition, the electric power source may comprise an internal combustion engine"],
    "US2020115045A1": ["may be powered electrically only, or it may be hybrid powered"],
    "US2020239134A1": ["can power the rotorcraft 101 without the need for the powerplant 155", "the powerplant 155 is a gas-fired turbine or combustion engine"],
    "US2020398977A1": ["Power source 132 may comprise a battery, a fuel cell, a generator"],
    "US2021122465A1": ["The aircraft 100 is a fully electric aircraft"],
    "US2021206487A1": ["are independently (i) battery powered; (ii) battery-hybrid powered or (iii) turbo-electrically powered"],
    "US2022169380A1": ["rechargeable batteries as one source of power", "at least one of the proprotors may have a hybrid propulsion system"],
    "US2022363374A1": ["in which an internal combustion engine such as the engine 50 is not mounted", "the generated electric power is stored in the battery 11"],
    "US2023211877A1": ["the energy for powering the electric motors may be stored in batteries", "In preferred embodiments, the aircraft carries an electricity generator"],
    "US2023331380A1": ["receive power from battery system 30", "Optionally, the power system of aircraft 10 could be a hybrid power system"],
    "US2024124134A1": ["provided by a battery system or a hybrid electric power system"],
    "US2024270378A1": ["an all-electric propulsion system 70", "electric batteries 81, which electrically power the electric motors", "a heat engine 80, e.g. a Diesel engine"],
    "WO2019211875A1": ["either all electric or hybrid/electric", "are used as the energy source in the all-electric version"],
    "US2025172947A1": ["may be electrically powered by rechargeable battery groups", "the VTOL aircraft 200 employs hybrid power"],
    "KR20220033079A": ["power may be delivered from the same battery (i) to the propulsion module", "further comprises a turbo generator that compresses and combusts air"],
    "US2019256200A1": ["provide the power to the rotor motor(s) when the engine(s) and the generator motor are turned off", "The second VTOL aerial vehicle variation being a hybrid"],
    # ---- A0: "hybrid" only in background / definitions / citations
    "US11688723B1": ["An electrical vertical take-off and landing (eVTOL) aircraft includes a plurality of electrical propulsion units", "Other proposed platforms are of the hybrid-electric type"],
    "US2021331791A1": ["Hybrid Electric Drive Train For VTOL Drones"],
    "US2022371727A1": ["the term eVTOL also includes VTOLs that use hybrid electric propulsion systems"],
    "US2023056974A1": ["EVTOL aircraft include VTOL aircraft that use a hybrid electric propulsion system"],
    "US2023118750A1": ["may use electric propulsion (motors, batteries, electronic controllers)", "Some eVTOL platforms may be hybrid-electric"],
    "US2020391861A1": ["a power supply such as an electric or hydraulic motor"],
    # ---- B: the engine makes the electricity; no battery-only flight stated
    "CN109263907A": ["uses internal combustion engine generator for battery charging"],
    "CN120191516A": ["an engine that operates with fuel to drive the generator, and A control means"],
    "FR3033363A1": ["the pilot disconnects the blower to couple a generator of electric current supplying at least an electrical motor"],
    "US2013099065A1": ["can be of a conventional configuration, with turbines and a gear unit", "comprises a hybrid drive which has for each propeller", "(so-called \"boost\")"],
    "US2018229606A1": ["An aircraft comprising: an electric power source comprising a combustion engine and an electric generator"],
    "US2018354615A1": ["to directly power electric motors 32 or for storage within batteries 30", "the electrical energy provided by the electrical energy generation system charges the batteries"],
    "US2018362160A1": ["power source 72 includes a battery 74, a generator 76, and a combustion engine 78"],
    "US2019071174A1": ["the power required to drive the electric motors comes from the electric generator"],
    "US2022097840A1": ["Three types of propulsion system suggested for this aircraft are"],
    "US2006151666A1": ["The power for the motors is derived from an internal combustion engine and generator, a fuel cell, or other source of electrical power"],
    "ES2288083A1": ["these are used to move the generators that drive the electric motors of the fans", "Electric motors can be powered with batteries, fuel cells, etc. during small periods of time"],
    "US2023312089A1": ["may instead include a combustion engine such as a turbine to drive an electric generator"],
    # ---- C: a combustion engine turns a propulsor
    "CN115258146A": ["a propeller 9 is fixedly arranged on the output shaft of the fuel engine 11"],
    "CN115447786A": ["the front wing engine is connected with a turbine fuel power system", "adopts a fuel and battery dual-energy mode"],
    "SK500442018A3": ["conventional propulsion engine with an internal combustion engine", "equipped with a generator (7) for charging the battery packs (6) during the forward flight"],
    "US2012234968A1": ["one of said engines comprises an internal combustion engine and the other of said engines comprises an electric motor"],
    "US2015314865A1": ["wherein a combustion engine drives, through a mechanical transmission, the rotors"],
    "US2016207625A1": ["wherein the thrust drive is driven by an internal combustion engine and the internal combustion engine is coupled to a generator"],
    "US2019023391A1": ["The forward thrust propulsor is selectively or permanently mechanically coupled to the combustion engine"],
    "US2019084684A1": ["a forward flight propeller driven by a liquid fuel engine"],
    "US2020262553A1": ["The power unit includes at least one electric powered motor and at least one jet fueled powered engine"],
    "US2021309351A1": ["the first propeller driven by the engine, a second propeller"],
    "US2022144443A1": ["a second propeller connected to the generator through a clutch"],
    "US2024025540A1": ["powered by a common electric generator located in the fuselage and driven by a heat engine", "the heat engine may serve both to drive the electric generator and to rotate the counter-rotating propeller"],
    "US2025136287A1": ["it is not necessary to provide for a battery for power supply"],
    "US2025353590A1": ["the prime mover of each of the one or more forward flight powertrains comprises an internal combustion engine"],
    "US2026001646A1": ["an engine mechanically coupled to the forward-motion propeller"],
    "DE102007055313A1": ["by means of turbo generators (14), which are operated by gas turbines", "instead of turbo generators (5) Solar cells are used"],
    "WO2021029947A2": ["hybrid electric-fuel engine, modular injection-molded structures"],
    "US2018141652A1": ["with the possibility to load this accumulator by means of a generator driven by the propulsion engines"],
    "CN118494752A": ["two fuel engines (22), a speed increasing gear box (23)", "four brushless motors (31) are powered by the lithium battery (32)"],
    # ---- E: not electric
    "US2008169375A1": ["a gas generator ( 200 a 1 ) for generating a turbine driving gas"],
    "US2009224096A1": ["Aircraft engines, and especially turboshaft engines, provide more power"],
    "WO2025065072A1": ["The engine is a turbine engine", "Alternatively, the internal combustion engine is a turbofan engine"],
    "US2025256840A1": ["The prime mover 52 may be an engine or other type of generator capable of transmitting rotation to the rotor systems"],
    # ---- D: the source is never named
    "CN112896499A": [],
    "US2020055595A1": [],
    "US2020148354A1": ["the power sources can be centralized in the fuselage"],
    "US2020307767A1": ["may further comprise a power source coupled to at least one of the airflow generator"],
    "FR3143549A1": [],
    "US2009008510A1": ["consist of one or more electric motors and/or combustion engines"],
    "DE102019006484B3": ["Inside the ship there is either an electrochemical energy store"],
}
